[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildDirectory = "backend"

[deploy]
startCommand = "python manage.py migrate && gunicorn blogbackend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.9.16"
DJANGO_SECRET_KEY = ")078o4o=cpufcrd@f8bl-s!fp$5i5j#l$^o=8xa)!vr4(=a08q"
DJANGO_DEBUG = "False"
ALLOWED_HOSTS = ".railway.app"
PORT = "8000"
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python39"]

[variables]
RAILWAY_DOCKERFILE_PATH = "backend/"
