services:
  - type: web
    name: blog-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blogbackend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

databases:
  - name: blog-db
    databaseName: blogdb
    user: blog_user
